In [1]:
from sklearn import tree
import pandas as pd
from sklearn import preprocessing
le = preprocessing.LabelEncoder()


In [2]:
dataset = pd.read_csv("loanstats2.csv")  
for column_name in dataset.columns:
        if dataset[column_name].dtype == object:
            dataset[column_name] = le.fit_transform(dataset[column_name])
        else:
            pass

In [3]:
dataset.shape  

(138, 8)

In [4]:
dataset.head()


Gender  Age  Married  Education  Self employed   Propety area  \
0       1    0        0          0               0             0   
1       0    0        0          2               0             0   
2       1    0        0          2               0             2   
3       1    1        1          0               0             0   
4       1    0        0          2               0             2   

   Monthly salary  Loan status  
0               0            1  
1               2            0  
2               0            1  
3               0            0  
4               0            0

In [5]:
X = dataset.drop('Loan status', axis=1)  
y = dataset['Loan status']  

In [6]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [7]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)  

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [8]:
y_pred = classifier.predict(X_test)  

In [9]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[ 6  8]
 [13 15]]
             precision    recall  f1-score   support

          0       0.32      0.43      0.36        14
          1       0.65      0.54      0.59        28

avg / total       0.54      0.50      0.51        42



In [10]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
# random forest model creation
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)

In [11]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
rfc_cv_score = cross_val_score(rfc, X, y, cv=10, scoring='roc_auc')

In [13]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))
print('\n')

=== Confusion Matrix ===
[[ 7  7]
 [12 16]]


=== Classification Report ===
             precision    recall  f1-score   support

          0       0.37      0.50      0.42        14
          1       0.70      0.57      0.63        28

avg / total       0.59      0.55      0.56        42





In [14]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [15]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [16]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [17]:
xg_reg.fit(X_train,y_train)

XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.3, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=5, min_child_weight=1, missing=None, n_estimators=10,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [18]:
preds = xg_reg.predict(X_test)

In [19]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, preds.round()))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, preds.round()))
print('\n')

=== Confusion Matrix ===
[[ 4 10]
 [12 16]]


=== Classification Report ===
             precision    recall  f1-score   support

          0       0.25      0.29      0.27        14
          1       0.62      0.57      0.59        28

avg / total       0.49      0.48      0.48        42



