In [91]:
from sklearn import tree
import pandas as pd
from sklearn import preprocessing
le = preprocessing.LabelEncoder()


In [92]:
dataset = pd.read_csv("loanstats2.csv")  
for column_name in dataset.columns:
        if dataset[column_name].dtype == object:
            dataset[column_name] = le.fit_transform(dataset[column_name])
        else:
            pass

In [93]:
dataset.shape  

(138, 8)

In [94]:
dataset.head()


Gender  Age  Married  Education  Self employed   Propety area  \
0       1    0        0          0               0             0   
1       0    0        0          2               0             0   
2       1    0        0          2               0             2   
3       1    1        1          0               0             0   
4       1    0        0          2               0             2   

   Monthly salary  Loan status  
0               0            1  
1               2            0  
2               0            1  
3               0            0  
4               0            0

In [95]:
X = dataset.drop('Loan status', axis=1)  
y = dataset['Loan status']  

In [96]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35)

In [97]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)  

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [98]:
y_pred = classifier.predict(X_test)  

In [99]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[11 14]
 [12 12]]
             precision    recall  f1-score   support

          0       0.48      0.44      0.46        25
          1       0.46      0.50      0.48        24

avg / total       0.47      0.47      0.47        49



In [100]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
# random forest model creation
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)

In [101]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

In [102]:
rfc_cv_score = cross_val_score(rfc, X, y, cv=10, scoring='roc_auc')

In [103]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))
print('\n')

=== Confusion Matrix ===
[[ 4 21]
 [10 14]]


=== Classification Report ===
             precision    recall  f1-score   support

          0       0.29      0.16      0.21        25
          1       0.40      0.58      0.47        24

avg / total       0.34      0.37      0.34        49





In [104]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [105]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [106]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [107]:
xg_reg.fit(X_train,y_train)

XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.3, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=5, min_child_weight=1, missing=None, n_estimators=10,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [108]:
preds = xg_reg.predict(X_test)

In [109]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, preds.round()))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, preds.round()))
print('\n')

=== Confusion Matrix ===
[[ 0 25]
 [ 1 23]]


=== Classification Report ===
             precision    recall  f1-score   support

          0       0.00      0.00      0.00        25
          1       0.48      0.96      0.64        24

avg / total       0.23      0.47      0.31        49



